[build]
builder = "nixpacks"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/v1/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"
